### ISSUE TITLE
PHP Error in core/functions/shared.php

### ISSUE THREAD

**Issue by jeremybuff** [awesomemotive/wp-simple-pay-lite#192]
The following error occurs on each page load:

`PHP Warning:  array_merge(): Expected parameter 1 to be an array, string given in /includes/core/functions/shared.php on line 121`

This error occurs within the `simpay_update_setting` function when merging `$existing_settings` and `$settings_to_update`. This occurs on page load, but watching my debug log it appears to happen randomly as well. 

Tested with both the lite and pro plugins on a totally fresh install: WP version 6.1.1 and on the Twenty Twenty-Three default theme. LAMP stack with PHP version 7.4.21.

**Comment by spencerfinnell** [comment]
Hello @jeremybuff

Thank you for the report. Unfortunately I'm not seeing this warning in my testing. Is it getting triggered in the admin, or frontend, or both?
